version: '3.8'

services:
  # Backend Service (Production Agents) - Main service
  backend:
    build:
      context: ./LokiAi
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SOCKET_PORT=5000
      - MONGODB_URI=mongodb://admin:lokiai2024@mongodb:27017/loki_agents?authSource=admin
      - CORS_ORIGIN=http://localhost:5000,http://localhost:5173,http://localhost:5175
    depends_on:
      - mongodb
    volumes:
      - ./LokiAi/logs:/app/logs
    networks:
      - lokiai-network

  # MongoDB Database
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=lokiai2024
      - MONGO_INITDB_DATABASE=loki_agents
    volumes:
      - mongodb_data:/data/db
      - ./LokiAi/mongodb-init.js:/docker-entrypoint-initdb.d/mongodb-init.js:ro
    networks:
      - lokiai-network

  # Rebalancer API (Flask Service)
  rebalancer-api:
    build:
      context: ./Rebalancer
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://admin:lokiai2024@mongodb:27017/loki_agents?authSource=admin
      - MONGO_DB_NAME=loki_agents
    depends_on:
      - mongodb
    networks:
      - lokiai-network

volumes:
  mongodb_data:

networks:
  lokiai-network:
    driver: bridge